dm_test:
  resource: "@DMTestBundle/Controller/"
  type:     annotation
  prefix:   /

core:
  resource: "@CoreBundle/Resources/config/routing.yml"
  prefix:   /

dm_contact:
  resource: "@DMContactBundle/Controller/DefaultController.php"
  prefix:   /
  type: annotation

dm_contact2:
  resource: "@DMContactBundle/Controller/ContactController.php"
  prefix:   /
  type: annotation
  
login:
  path: /login
  defaults:
    _controller: UserBundle:Security:login
 
login_check:
  path: /login_check

logout:
  path: /logout
  
