core:
    resource: "@CoreBundle/Resources/config/routing.yml"
    prefix:   /

dm_contact:
    resource: "@DMContactBundle/Resources/config/routing.yml"
    prefix:   /
  
login:
  path: /login
  defaults:
    _controller: UserBundle:Security:login
 
login_check:
  path: /login_check

logout:
  path: /logout
  
